name: Tests

on:
  push:
    branches: [main, claude/**]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --all-extras

      - name: Run ruff check
        run: uv run ruff check src/

      - name: Run ruff format check
        run: uv run ruff format --check src/

      - name: Run mypy
        run: uv run mypy src/gamedatagen/ --no-error-summary || true

      - name: Run tests
        run: uv run pytest tests/ -v || echo "No tests found"

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        run: uv python install 3.11

      - name: Install dependencies
        run: uv sync

      - name: Run ruff
        run: uv run ruff check src/

      - name: Check formatting
        run: uv run ruff format --check src/
